sudo cp /home/lun5/Documents/multiplex/output/Entropy_radius_50_alpha_0.1_L1ratio_0/*.png /mnt/lun5/ColonCancerStudy/Entropy_data/Entropy_radius_50_alpha_0.1_L1ratio_0
sudo cp /home/lun5/Documents/multiplex/output/Entropy_radius_50_alpha_0.1_L1ratio_0.5/*.png /mnt/lun5/ColonCancerStudy/Entropy_data/Entropy_radius_50_alpha_0.1_L1ratio_0.5
sudo cp /home/lun5/Documents/multiplex/output/Entropy_radius_50_alpha_0.1_L1ratio_1/*.png /mnt/lun5/ColonCancerStudy/Entropy_data/Entropy_radius_50_alpha_0.1_L1ratio_1
sudo cp /home/lun5/Documents/multiplex/output/Entropy_radius_100_alpha_0.1_L1ratio_0/*.png /mnt/lun5/ColonCancerStudy/Entropy_data/Entropy_radius_100_alpha_0.1_L1ratio_0
sudo cp /home/lun5/Documents/multiplex/output/Entropy_radius_100_alpha_0.1_L1ratio_0.5/*.png /mnt/lun5/ColonCancerStudy/Entropy_data/Entropy_radius_100_alpha_0.1_L1ratio_0.5
sudo cp /home/lun5/Documents/multiplex/output/Entropy_radius_100_alpha_0.1_L1ratio_1/*.png /mnt/lun5/ColonCancerStudy/Entropy_data/Entropy_radius_100_alpha_0.1_L1ratio_1
sudo cp /home/lun5/Documents/multiplex/output/Entropy_radius_50_alpha_1_L1ratio_0/*.png /mnt/lun5/ColonCancerStudy/Entropy_data/Entropy_radius_50_alpha_1_L1ratio_0
sudo cp /home/lun5/Documents/multiplex/output/Entropy_radius_50_alpha_1_L1ratio_0.5/*.png /mnt/lun5/ColonCancerStudy/Entropy_data/Entropy_radius_50_alpha_1_L1ratio_0.5
sudo cp /home/lun5/Documents/multiplex/output/Entropy_radius_50_alpha_1_L1ratio_1/*.png /mnt/lun5/ColonCancerStudy/Entropy_data/Entropy_radius_50_alpha_1_L1ratio_1
sudo cp /home/lun5/Documents/multiplex/output/Entropy_radius_100_alpha_1_L1ratio_0/*.png /mnt/lun5/ColonCancerStudy/Entropy_data/Entropy_radius_100_alpha_1_L1ratio_0
sudo cp /home/lun5/Documents/multiplex/output/Entropy_radius_100_alpha_1_L1ratio_0.5/*.png /mnt/lun5/ColonCancerStudy/Entropy_data/Entropy_radius_100_alpha_1_L1ratio_0.5
sudo cp /home/lun5/Documents/multiplex/output/Entropy_radius_100_alpha_1_L1ratio_1/*.png /mnt/lun5/ColonCancerStudy/Entropy_data/Entropy_radius_100_alpha_1_L1ratio_1
